version: '3.8'

services:
  front:
      build:
        context: .
        dockerfile: Dockerfile.front
      # ports:
      #   - 5000:5000
      container_name: ex_2.3_front

  back:
      build:
        context: .
        dockerfile: Dockerfile.back
      # ports:
      #   - 8080:8080
      environment:
        REDIS_HOST: redis_host
        POSTGRES_HOST: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: postgres
        REQUEST_ORIGIN : http://localhost
      container_name: ex_2.3_back

  redis_host:
      image: redis
      restart: unless-stopped
      command: redis-server
      container_name: redis_host

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
        POSTGRES_HOST: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: postgres
    volumes:
        - type: bind
          source: ./database
          target: /var/lib/postgresql/data
    container_name: postgres

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - front
      - back