FROM node:16


WORKDIR /usr/src/app

RUN git clone https://github.com/docker-hy/material-applications

# EXPOSE 5000
# ENV REACT_APP_BACKEND_URL=http://127.0.0.1:8080
COPY . .

WORKDIR material-applications/example-frontend/

#WORKDIR  /usr/src/app
#/usr/src/app/material-applications/example-frontend
RUN npm install
COPY . .
# COPY /usr/src/app/material-applications/example-frontend/package.json /usr/src/app/package.json
RUN npm run build
RUN npm install -g serve
CMD ["serve", "-s", "-l", "5000", "build"]