FROM golang:1.16-alpine

WORKDIR /usr/src/app
RUN apk add git && git clone https://github.com/docker-hy/material-applications

COPY . .

WORKDIR material-applications/example-backend

RUN addgroup -S appuser && adduser -S appuser && chown appuser /usr/src/app/material-applications/example-backend && go build

EXPOSE 8080
ENV REQUEST_ORIGIN=http://127.0.0.1:5000

USER appuser
CMD ["./server"]


