FROM node:16-alpine

EXPOSE 5000
WORKDIR /usr/src/app
ENV REACT_APP_BACKEND_URL=http://127.0.0.1:8080
RUN apk add git && git clone https://github.com/docker-hy/material-applications

COPY . .

WORKDIR material-applications/example-frontend/
COPY . .

RUN npm install && npm run build && npm install -g serve && addgroup -S appuser \
        && adduser -S appuser && chown appuser .

USER appuser
CMD ["serve", "-s", "-l", "5000", "build"]