FROM openjdk:8-jdk-alpine as build-stage

WORKDIR /usr/src/app
RUN apk add git && apk add maven && git clone https://github.com/docker-hy/material-applications
COPY . .

WORKDIR material-applications/spring-example-project
# RUN addgroup -S appuser && adduser -S appuser
# RUN chown appuser /usr/src/app/material-applications/spring-example-project
RUN ./mvnw package
COPY . .

FROM scratch
# COPY --from=build-stage /built-server /built-server
COPY --from=build-stage /usr/src/app/material-applications/spring-example-project/target/docker-example-1.1.3.jar ./target/docker-example-1.1.3.jar
CMD ["java", "-jar",  "./target/docker-example-1.1.3.jar"]
EXPOSE 8080